# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram1', '0002_auto_20191020_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
